events {}

http {
    map_hash_bucket_size 128;

    include /etc/nginx/secrets/telemetry-auth.conf;

    server {
        listen 8080;
        listen 8443 ssl;

        ssl_certificate     /etc/nginx/secrets/tls/telemetry.crt;
        ssl_certificate_key /etc/nginx/secrets/tls/telemetry.key;

        client_max_body_size 10m;

        location = /health {
            default_type text/plain;
            return 200 "ok\n";
        }

        location /loki/api/v1/push {
            if ($authorized_node = 0) {
                return 401;
            }

            proxy_pass http://loki:3100;

            proxy_http_version 1.1;
            proxy_set_header Host $host;

            proxy_set_header X-Scope-OrgID "NS-C001";
        }
    }
}