services:
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    restart: unless-stopped

    command: -config.file=/etc/loki/local-config.yaml

    volumes:
      - ./configs/loki:/etc/loki
      - loki-data:/tmp/loki

    networks:
      - network-sentinel

  telemetry-gateway:
    image: nginx:alpine
    container_name: telemetry-gateway
    restart: unless-stopped

    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - network-sentinel

    depends_on:
      - loki

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped

    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

    ports:
      - "12345:12345"

    volumes:
      - ./configs/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /home/daw/Network-Sentinel/Docker/suricata/logs:/var/log/suricata:ro
      - alloy-data:/var/lib/alloy/data

    networks:
      - network-sentinel

    depends_on:
      - loki

volumes:
  loki-data:
  alloy-data:

networks:
  network-sentinel:
    external: true