services:
  ai-backend:
    build: .
    container_name: ai-backend

    ports:
      - "5000:5000"

    networks:
      - network-sentinel

    environment:
      LOKI_TENANT_ID: ${LOKI_TENANT_ID}

    restart: unless-stopped

networks:
  network-sentinel:
    external: true