services:
  ai-backend:
    build: .
    container_name: ai-backend

    ports:
      - "5000:5000"

    networks:
      - network-sentinel

    restart: unless-stopped

networks:
  network-sentinel:
    external: true